# Generated by Django 5.2.3 on 2025-07-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=100)),
                ('generation', models.CharField(max_length=100)),
                ('car_body', models.CharField(max_length=100)),
                ('engine_capacity', models.FloatField()),
                ('mileage', models.IntegerField()),
                ('drivetrain', models.CharField(max_length=100)),
                ('drive_type', models.CharField(max_length=50)),
                ('steering_wheel', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
