# Generated by Django 5.2.3 on 2025-07-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_benz', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
