# Generated by Django 5.2.3 on 2025-07-24 09:46

import m_benz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_benz', '0005_car_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to=m_benz.models.car_image_upload_path),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
